package com.techflag.workdsh.admin;
import java.util.*;import java.io.*;import java.net.http.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.test.context.ActiveProfiles;import org.springframework.mock.web.MockHttpServletRequest;import org.springframework.test.util.ReflectionTestUtils;import org.springframework.web.server.ResponseStatusException;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
@SpringBootTest(properties={"spring.datasource.url=jdbc:sqlite:file:gateway-test?mode=memory&cache=shared","workdsh.bootstrap.admin-email=gateway-admin@example.test","workdsh.bootstrap.admin-password=GatewayAdminPassword123!","workdsh.secrets.encryption-key=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="}) @ActiveProfiles("enterprise-sqlite")
class ModelGatewayTest {
 @Autowired org.springframework.jdbc.core.JdbcTemplate db;@Autowired ModelGateway gateway;@Autowired ModelProvidersController providers;@Autowired com.fasterxml.jackson.databind.ObjectMapper json;@Autowired AuthService auth;
 @Test void apiUsesInternalKeyAndInjectsSupplierKeyWithoutCustomDshAdapter() throws Exception {
 var login=auth.login("gateway-admin@example.test","GatewayAdminPassword123!");String bearer="Bearer "+login.token();var actor=auth.actor(bearer);String key="internal-test-access-key-with-32-characters",next="rotated-test-access-key-with-32-characters";
 providers.update(bearer,new ModelProviders.Update(0,List.of(new ModelProviders.Provider("company","Company","https://api.deepseek.com","openai-completions",true,List.of(new ModelProviders.Model("deepseek-flash","Flash",null,null,false)),false,"supplier-secret-fixture")),key));assertEquals(actor.organizationId(),gateway.authorize("Bearer "+key,null).org());assertEquals(401,assertThrows(ResponseStatusException.class,()->gateway.authorize("Bearer wrong",null)).getStatusCode().value());assertFalse(gateway.read(bearer).toString().contains(key));assertTrue(gateway.catalog("Bearer "+key,null).toString().contains("deepseek-flash"));
 var request=new MockHttpServletRequest();request.setRequestURI("/api/model-gateway/v1/chat/completions");assertEquals(403,assertThrows(ResponseStatusException.class,()->gateway.forward(request,"Bearer "+key,null,"{\"model\":\"foreign\"}".getBytes())).getStatusCode().value());
 var server=com.sun.net.httpserver.HttpServer.create(new java.net.InetSocketAddress("127.0.0.1",0),0);
 var capturedKey=new java.util.concurrent.atomic.AtomicReference<String>();
 server.createContext("/v1/chat/completions",exchange->{capturedKey.set(exchange.getRequestHeaders().getFirst("Authorization"));exchange.getRequestBody().readAllBytes();exchange.getResponseHeaders().set("Content-Type","text/event-stream");exchange.sendResponseHeaders(200,0);try(var out=exchange.getResponseBody()){out.write("data: {\"id\":\"test\",\"object\":\"chat.completion.chunk\",\"created\":1,\"model\":\"deepseek-flash\",\"choices\":[{\"index\":0,\"delta\":{\"content\":\"fixture\"},\"finish_reason\":null}]}\n\ndata: [DONE]\n\n".getBytes());}});
 server.start();
 try {
  // Test-only local upstream; production configuration still requires HTTPS.
  var config=json.readTree(db.queryForObject("select providers_json from organization_model_providers where organization_id=?",String.class,actor.organizationId()));((com.fasterxml.jackson.databind.node.ObjectNode)config.get(0)).put("baseUrl","http://127.0.0.1:"+server.getAddress().getPort());db.update("update organization_model_providers set providers_json=? where organization_id=?",json.writeValueAsString(config),actor.organizationId());
  var response=gateway.forward(request,"Bearer "+key,null,"{\"model\":\"deepseek-flash\",\"messages\":[{\"role\":\"user\",\"content\":\"test\"}],\"stream\":true}".getBytes());var output=new ByteArrayOutputStream();response.getBody().writeTo(output);assertTrue(output.toString().contains("fixture"));assertTrue(output.toString().endsWith("data: [DONE]\n\n"));assertEquals("Bearer supplier-secret-fixture",capturedKey.get());assertFalse(output.toString().contains(key));
 } finally {server.stop(0);}

 gateway.update(bearer,new ModelGateway.Update(next));assertEquals(401,assertThrows(ResponseStatusException.class,()->gateway.authorize("Bearer "+key,null)).getStatusCode().value());assertEquals(actor.organizationId(),gateway.authorize(null,next).org());assertEquals(400,assertThrows(ResponseStatusException.class,()->gateway.forward(request,null,next,"{}".getBytes())).getStatusCode().value());
 }
}
